### PR TITLE
activerecord: Add ActiveRecord::Base.generates_tokens_for

### PR DESCRIPTION
**Pull request by tk0miya**
`ActiveRecord::Base.generates_token_for` has been added since v7.1.

refs:

* https://github.com/rails/rails/pull/44189
* https://github.com/rails/rails/blob/v7.1.4/activerecord/CHANGELOG.md

### CODE REVIEW

**Review by ksss — COMMENTED** [review]
APPROVE

**Comment by tk0miya** [comment]
Fixed conflicts. Could you approved this again?

**Review by ksss — COMMENTED** [review]
APPROVE

**Comment by tk0miya** [comment]
Thanks!

**Pull request merged**
