### PR TITLE
activerecord: Fix type of #merge

### PR DESCRIPTION
**Pull request by tk0miya**
The #merge method can take the relation object for other models:

    Account.joins(:articles).merge(Articles.where(...))

### CODE REVIEW

**Comment by ksss** [comment]
It looks like `ActiveRecord::SpawnMethods#merge` will also accept `Array`, `Hash`, and `#to_proc`

```rb
    def merge(other, *rest)
      if other.is_a?(Array)
        records & other
      elsif other
        spawn.merge!(other, *rest)
      else
        raise ArgumentError, "invalid argument: #{other.inspect}."
      end
    end

    def merge!(other, *rest) # :nodoc:
      options = rest.extract_options!
      if other.is_a?(Hash)
        Relation::HashMerger.new(self, other, options[:rewhere]).merge
      elsif other.is_a?(Relation)
        Relation::Merger.new(self, other, options[:rewhere]).merge
      elsif other.respond_to?(:to_proc)
        instance_exec(&other)
      else
        raise ArgumentError, "#{other.inspect} is not an ActiveRecord::Relation"
      end
    end
```

https://api.rubyonrails.org/classes/ActiveRecord/SpawnMethods.html#method-i-merge

**Comment by tk0miya** [comment]
Thank you for reviewing. Updated!

**Comment by pocke** [comment]
It looks good but this change conflict with the default branch. Could you resolve the conflict?

**Comment by tk0miya** [comment]
The conflict is resolved now.

**Review by pocke — APPROVED** [review]
Thanks!

**Pull request merged**
