### PR TITLE
Add record_timestamps argument to insert_all and similar methods

### PR DESCRIPTION
**Pull request by rhiroe**
The record_timestamps argument has been added to insert_all and similar methods since ActiveRecord7.0.

ref: https://github.com/rails/rails/pull/43003

### CODE REVIEW

**Comment by rhiroe** [comment]
https://github.com/ruby/gem_rbs_collection/issues/619

**Review by ksss — COMMENTED** [review]
APPROVE

**Comment by rhiroe** [comment]
Executed rebase.

**Comment by rhiroe** [comment]
😭 
@ksss Sorry, please "APPROVE" again.

**Review by ksss — COMMENTED** [review]
APPROVE 👍

**Pull request merged**
