### PR TITLE
Add Types for ActiveSupport::SecurityUtils

### PR DESCRIPTION
**Pull request by m11o**
Add types for `secure_compare` and `fixed_length_secure_compare` methods in ActiveSupport::SecurityUtils

ref: https://github.com/rails/rails/blob/v6.0.6.1/activesupport/lib/active_support/security_utils.rb

### CODE REVIEW

**Review by pocke — APPROVED** [review]

**Comment by pocke** [comment]
Please fix the conflict.

**Comment by m11o** [comment]
Thank you for your review. I fixed it.

**Review by pocke — APPROVED** [review]
Thanks! Sorry for my absence 🙏

**Comment by m11o** [comment]
No problem! 👍 I always appreciate your reviews.

**Pull request merged**
