### PR TITLE
activerecord: Add ActiveRecord::QueryMethods#with

### PR DESCRIPTION
**Pull request by tk0miya**
refs:

* https://github.com/rails/rails/blob/7-1-stable/activerecord/CHANGELOG.md
* https://api.rubyonrails.org/classes/ActiveRecord/QueryMethods.html#method-i-with

### CODE REVIEW

**Review by ksss — COMMENTED** [review]
APPROVE

**Comment by tk0miya** [comment]
Oops... we need to re-approve if I fixed the conflicts.

@ksss could you review this again, please?

**Review by ksss — COMMENTED** [review]
APPROVE

**Pull request merged**
