### PR TITLE
activerecord: Support insert_all on relation (for Rails 7.2)

### PR DESCRIPTION
**Pull request by tk0miya**
ActiveRecord supports insert and upsert methods on relation classes (AssociationRelation and CollectionProxy) since v6.1.

The implementation of insert_all has been changed since v7.2. The implementation was moved to AR::Relation from AR::Persistence.  So types follow the new structure.

refs:

* #658
* https://github.com/rails/rails/pull/38899
* https://github.com/rails/rails/pull/51805
* https://github.com/rails/rails/blob/v6.1.7.8/activerecord/CHANGELOG.md

### CODE REVIEW

**Review by ksss — COMMENTED** [review]
APPROVE

**Comment by tk0miya** [comment]
Fixed conflicts. I'm very sorry...

**Review by ksss — COMMENTED** [review]
APPROVE

**Pull request merged**
