### PR TITLE
activerecord: Add types for strict_loading

### PR DESCRIPTION
**Pull request by dak2**
Add types for below three methods.

- strict_loading(value = true)
  - https://api.rubyonrails.org/v6.1.7.3/classes/ActiveRecord/QueryMethods.html#method-i-strict_loading
- strict_loading?()
  - https://api.rubyonrails.org/v6.1.7.3/classes/ActiveRecord/Core.html#method-i-strict_loading-3F
- strict_loading!()
  - https://api.rubyonrails.org/v6.1.7.3/classes/ActiveRecord/Core.html#method-i-strict_loading-21

Arguments have been added to strict_loading! since 7.0.

- up to 6.1
  - https://api.rubyonrails.org/v6.1.7.3/classes/ActiveRecord/Core.html#method-i-strict_loading-21
- since 7.0
  - https://api.rubyonrails.org/v7.0/classes/ActiveRecord/Core.html#method-i-strict_loading-21

This methods have been added since 6.1.

https://github.com/rails/rails/pull/37400

### CODE REVIEW

**Review by ksss — COMMENTED** [review]
APPROVE

**Comment by dak2** [comment]
@ksss 

Could you re-review this pr ?

I rebased master branch to run `Test / test_rubocop_yml` workflow it was added by https://github.com/ruby/gem_rbs_collection/pull/757. So, I need re-approval.

**Review by ksss — COMMENTED** [review]
APPROVE

**Comment by dak2** [comment]
@ksss 

Thanks!

**Pull request merged**
