### PR TITLE
Make block argument optional for ActiveSupport Methods

### PR DESCRIPTION
**Pull request by Adrian-Hirt**
In advance, thanks for this repo, it's really useful to already have RBS for gems!
When I used the `activesupport` from this repo in steep, I noticed that some methods require me to define an empty block, for example, this will fail:

```ruby
module Animals
  mattr_accessor :animal_kinds
end
```

When running `steep check`, the output is:

```
lib/animals.rb:2:2: [error] Cannot find compatible overloading of method `mattr_accessor` of type `singleton(::Animals)`
│ Method types:
│   def mattr_accessor: (*untyped, ?instance_reader: bool, ?instance_writer: bool, ?instance_accessor: bool, ?default: untyped) { () -> untyped } -> untyped
│
│ Diagnostic ID: Ruby::UnresolvedOverloading
│
└   mattr_accessor :animal_kinds
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This is because the block argument for the `mattr_accessor` is required, and as such, if passing in an empty block, the above works:

```ruby
module Animals
  mattr_accessor :animal_kinds do; end
end
```

I adapted the methods that I found that have an optional block argument. I might not have picked up all, but the most important ones should be working.

Please let me know if you'd like any other adaptions.

Regards

Adrian

### CODE REVIEW

**Comment by Adrian-Hirt** [comment]
I just noticed when looking at #4 that the `activesupport-generated.rbs` file only contains the automatically generated definitions, and as such, I moved the adaptions to an external file called `activesupport.rbs`.

Please let me know if anything needs to be otherwise changed or if my adaptions contain some mistakes. I'm relatively new to working with RBS, but I think it's a really cool feature and incredibly useful :smile: 

Regards

Adrian

**Comment by pocke** [comment]
Thank you for the pull request! And sorry for my absence. 




Currently the added RBS causes errors because it has duplicate method definitions. RBS doesn't allow duplicate method definitions. For example:

```rbs
# RBS

class C
  def foo: () -> untyped
end

class C
  def foo: () -> untyped
end
```


```bash
$ rbs -I. validate --silent
/home/pocke/.rbenv/versions/trunk/lib/ruby/gems/3.1.0/gems/rbs-1.0.6/lib/rbs/definition_builder/method_builder.rb:30:in `block in validate!': test.rbs:4:2...4:24: ::C#foo has duplicated definitions in test.rbs:8:2...8:24 (RBS::DuplicatedMethodDefinitionError)
	from /home/pocke/.rbenv/versions/trunk/lib/ruby/gems/3.1.0/gems/rbs-1.0.6/lib/rbs/definition_builder/method_builder.rb:28:in `each_value'
	from /home/pocke/.rbenv/versions/trunk/lib/ruby/gems/3.1.0/gems/rbs-1.0.6/lib/rbs/definition_builder/method_builder.rb:28:in `validate!'
	from /home/pocke/.rbenv/versions/trunk/lib/ruby/gems/3.1.0/gems/rbs-1.0.6/lib/rbs/definition_builder/method_builder.rb:123:in `build_instance'
	from /home/pocke/.rbenv/versions/trunk/lib/ruby/gems/3.1.0/gems/rbs-1.0.6/lib/rbs/definition_builder.rb:147:in `block (2 levels) in build_instance'
	from <internal:kernel>:90:in `tap'
	from /home/pocke/.rbenv/versions/trunk/lib/ruby/gems/3.1.0/gems/rbs-1.0.6/lib/rbs/definition_builder.rb:145:in `block in build_instance'
	from /home/pocke/.rbenv/versions/trunk/lib/ruby/gems/3.1.0/gems/rbs-1.0.6/lib/rbs/definition_builder.rb:776:in `try_cache'
	from /home/pocke/.rbenv/versions/trunk/lib/ruby/gems/3.1.0/gems/rbs-1.0.6/lib/rbs/definition_builder.rb:135:in `build_instance'
	from /home/pocke/.rbenv/versions/trunk/lib/ruby/gems/3.1.0/gems/rbs-1.0.6/lib/rbs/cli.rb:423:in `block in run_validate'
	from /home/pocke/.rbenv/versions/trunk/lib/ruby/gems/3.1.0/gems/rbs-1.0.6/lib/rbs/cli.rb:421:in `each_key'
	from /home/pocke/.rbenv/versions/trunk/lib/ruby/gems/3.1.0/gems/rbs-1.0.6/lib/rbs/cli.rb:421:in `run_validate'
	from /home/pocke/.rbenv/versions/trunk/lib/ruby/gems/3.1.0/gems/rbs-1.0.6/lib/rbs/cli.rb:113:in `run'
	from /home/pocke/.rbenv/versions/trunk/lib/ruby/gems/3.1.0/gems/rbs-1.0.6/exe/rbs:7:in `<top (required)>'
	from /home/pocke/.rbenv/versions/trunk/bin/rbs:23:in `load'
	from /home/pocke/.rbenv/versions/trunk/bin/rbs:23:in `<main>'
```


So, it needs to `...` to avoid the errors by defining overloads. For example:

```rbs
# RBS

class C
  def foo: () -> untyped
end

class C
  def foo: () -> untyped
         | ...
end
```


```bash
$ rbs -I. validate --silent
# it is ok
```



Could you add `...` to the added methods? It will fix the errors.



You can test the RBS files with the test script under `gems/railties/6.0.3.2`.

```bash
$ cd gems/railties/6.0.3.2
$ ./_script/test # It run rbs validate, and steep on rbs_rails repository
```



I confirmed the test script works well with the latest main branch of this repository. So if you have any trouble, rebasing to the main may solve it.
If you have any trouble, feel free to ping me.

Thanks!

**Comment by Adrian-Hirt** [comment]
Hello @pocke, thank you for reviewing and no worries about the time, it's not really an urgent pull request :)

I changed the method definitions, running `_script/test` in `gems/activesupport/6.0.3.2` now validates all the definitions.

About the `...` notation for overlolading:
I'm not sure if I checked at all the correct places, but looking at the [Syntax Guide](https://github.com/ruby/rbs/blob/master/docs/syntax.md) from RBS, I did not find this notation.
Looking at https://github.com/ruby/rbs/blob/master/lib/rbs/parser.y#L429, it seems that for overloading methods from another file (or simply another definition), one needs to either use the keyword `overloaded` (which is deprecated), or use the `...` syntax (i.e. specify the `...` as last method type). Should I open an Issue / a PR in the rbs repo for this, or did I simply overlook it?

Regards

Adrian

**Review by pocke — APPROVED** [review]
Thanks! :+1:

**Comment by pocke** [comment]
> Should I open an Issue / a PR in the rbs repo for this, or did I simply overlook it?


Good catch :+1:  Could you open an issue or pull request in ruby/rbs repository? I think the lack of the documentation of `...` syntax is not intentional. The documentation should mention `...` syntax.

**Comment by Adrian-Hirt** [comment]
@pocke Thanks for merging. Yes, I will open a PR in the RBS repo with the fixed documentation :+1:

**Pull request merged**
