### PR TITLE
switching aws s3 body type to Types::body

### PR DESCRIPTION
**Pull request by HoneyryderChuck**
Types::body can either be an IO or a String (the latter was missing for the type to be considered complete)

### CODE REVIEW

**Comment by ksss** [comment]
@HoneyryderChuck Thank you for your contribution.

rbs files under `gems/aws-sdk-*` are files generated by aws-sdk-rbs-generator.
So it cannot be merged as it is.

I will fix the problem.
If you can create an issue, I can refer to it.

**Comment by HoneyryderChuck** [comment]
@ksss thx for the feedback. FYI I was also planning to add signatures for aws-sdk-sns and aws-sdk-firehose (as those are the ones I have immediate interest in). Am I correct to assume that I should add them in the generator?

**Comment by ksss** [comment]
Great.
aws-sdk-sns and aws-sdk-firehose are easy to add.
I'm considering a policy of adding them when requested.
I'll add them here when https://github.com/ruby/gem_rbs_collection/pull/354 is done.

**Comment by ksss** [comment]
aws-sdk-sns and aws-sdk-firehose have already been added.
Please check here. https://github.com/ruby/gem_rbs_collection/issues/355

**Comment by HoneyryderChuck** [comment]
Thx for the update, will close this then.

**Pull request closed without merging**
