### PR TITLE
Add YARD gem and generator

### PR DESCRIPTION
**Pull request by ksss**
I developed a tool to generate RBS from YARD tags and applied it to YARD gem to generate RBS.

### CODE REVIEW

**Comment by pocke** [comment]
Could you commit the generator? Everyone else cannot modify the RBSs except you if the generator is unavailable in this repository.

**Comment by ksss** [comment]
@pocke 
I've committed the generator and regenerated!

**Review by pocke — APPROVED** [review]

**Review by pocke — CHANGES_REQUESTED** [review]
Ah, I merged main branch then the rbs is broken due to rack definition. Could you fix that?

**Comment by ksss** [comment]
I fixed dependency for rack.
And also add to call check-untyped-call.rb on `_scripts/test`

**Review by pocke — APPROVED** [review]
👍

**Pull request merged**
