### PR TITLE
[httparty] Add RBS files for HTTParty(0.18.1) gem

### PR DESCRIPTION
**Pull request by raosush**
# Description
### Complete RBS write-up of [HTTParty(0.18.1)](https://github.com/jnunemaker/httparty)
- Added RBS files for HTTParty (0.18.1)
- Added test script in _scripts folder to run `rbs validate` & `steep check`
- Added tests & Steepfile in _test folder
- Added git module referencing the source code of the gem

Signed-off-by: Sushanth Sathesh Rao <rao.sush004@gmail.com>

### CODE REVIEW

**Comment by raosush** [comment]
- [ ] Update the test script & Steepfile to require `Net::HTTP`, once RBS for `Net::HTTP` is added into `rbs/stdlib`

**Comment by pocke** [comment]
Thanks for your pull request!



Could you move the directory from `gems/httparty/0.18.1/` to ` gems/httparty/0.18/`?

> Specify the major and minor version you are using would be great for most cases.
>
> https://github.com/ruby/gem_rbs_collection#make-a-directory



---



This patch depends on https://github.com/ruby/rbs/pull/686, so we need to review https://github.com/ruby/rbs/pull/686 before reviewing this pull request.

**Comment by raosush** [comment]
> This patch depends on ruby/rbs#686, so we need to review ruby/rbs#686 before reviewing this pull request.

`Net::HTTP` is internally used by `HTTParty` and hence ruby/rbs#686 would need to be reviewed & merged into [ruby/rbs](https://github.com/ruby/rbs) prior to this PR.

> Could you move the directory from gems/httparty/0.18.1/ to gems/httparty/0.18/?

Moved the directory from `gems/httparty/0.18.1` to `gems/httparty/0.18`

**Review by soutaro — APPROVED** [review]
👍

**Pull request merged**
