### PR TITLE
Fixed steep error points in ActiveRecord 6.1

### PR DESCRIPTION
**Pull request by rhiroe**
resolved https://github.com/ruby/gem_rbs_collection/issues/619

- Symlink of _test/metadata.yaml in 6.0 to 6.1
- Annotated `User#articles` definition using `@dynamic` and removed _test/steep_expectations.yml

### CODE REVIEW

**Comment by rhiroe** [comment]
I am not sure how Steep errors came to be ignored.
@tk0miya Any supplemental information would be appreciated.

**Comment by rhiroe** [comment]
Maybe it would be better to create a symbolic link instead of adding a file.

**Comment by tk0miya** [comment]
It's much better to use symlinks for these files than copying them.

**Comment by tk0miya** [comment]
Looks good. Thanks!

**Comment by ksss** [comment]
APPROVE

**Review by ksss — COMMENTED** [review]
APPROVE

**Pull request merged**
