### PR TITLE
Update Rack RBS to 2.2.4

### PR DESCRIPTION
**Pull request by ParadoxV5**
This PR updates `rack` RBS to Rack 2.2.4 by incorporating [diffs between 2.2.2 and 2.2.4](https://github.com/rack/rack/compare/v2.2.2...2.2.4).

This PR directly `git mv` the 2.2.2 RBS and `_test` files to the 2.2.4 directory. Because Rack’s RBS has untyped entries and potentially-incorrect types (#210), I determined it is not suitable for production (yet?) and did not keep the 2.2.2 directory. This PR does *not* address the aforementioned content issues.

I ran `steep check` using Bundler (to constraint Rack’s version to 2.2.4, `Gemfile`/`.lock` not checked in) and `No type error detected. 🧋`

### CODE REVIEW

**Comment by pocke** [comment]
Could you move the directory from `rack/2.2.2/` to `rack/2.2.4/`? 


Basically, the version should be `MAJOR.MINOR`, but without a patch version. Patch versions don't have interface changes in most cases, so it is not necessary that we make other directories for each patch version.

https://github.com/ruby/gem_rbs_collection/blob/dc7059ea0cdf67f486ca9cea2b01d53f04724652/docs/CONTRIBUTING.md#generate-a-boilerplate

**Comment by ParadoxV5** [comment]
> Could you move the directory from `rack/2.2.2/` to `rack/2.2.4/`?

Aren’t they already moved, @pocke? Or did you mean to move to `rack/2.2`?

> Patch versions don't have interface changes in most cases

That is correct. IIRC, there were no method changes between 2.2.2 and 2.2.4, although there were minor differences in the exposed internals that one *could* (but unlikely *would*) use.

**Comment by pocke** [comment]
> Aren’t they already moved, @pocke? Or did you mean to move to rack/2.2?


Ah, sorry. I meant moving to `rack/2.2` 🙈 Could you rename the directory?

**Comment by ParadoxV5** [comment]
👌

**Review by pocke — APPROVED** [review]
Thanks!

**Pull request merged**
